g_metacoq_verified_malfunction.cmx: compile_malfunction.cmx
	ocamlfind opt ${CAMLFLAGS} ${FINDLIBPKGS} -c  -for-pack Metacoq_verified_malfunction_plugin compile_malfunction.mli g_metacoq_verified_malfunction.ml

metacoq_verified_malfunction_plugin.cmx: primInt63.cmx float64_common.cmx primFloat.cmx compile_malfunction.cmx
	ocamlfind opt ${CAMLFLAGS} ${FINDLIBPKGS} -pack -o $@ $+
